"""empty message

Revision ID: 216951f77a7f
Revises: 5d64ddcb33c4
Create Date: 2025-02-18 10:04:16.018368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "216951f77a7f"
down_revision = "5d64ddcb33c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_login")

    # ### end Alembic commands ###
