"""empty message

Revision ID: 5d64ddcb33c4
Revises: 1f62f008fb88
Create Date: 2025-02-18 08:43:01.057812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d64ddcb33c4"
down_revision = "1f62f008fb88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("hash_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_url_hash_id"), ["hash_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_hash_id"))

    op.drop_table("url")
    # ### end Alembic commands ###
